.TH "AbstractFeature" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractFeature \- Classe abstrata que representa a estrutura básica de um atributo\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCaseFeature\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractFeature\fP (int \fBid\fP, string \fBname\fP, Type \fBtype\fP)"
.br
.RI "Construtor da classe \fBAbstractFeature\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Identificador do atributo\&. "
.ti -1c
.RI "string \fBname\fP"
.br
.RI "Nome do atributo\&. "
.ti -1c
.RI "string \fBtype\fP"
.br
.RI "Tipo de dado do atributo\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe abstrata que representa a estrutura básica de um atributo\&. 


.PP
Definition at line 8 of file AbstractFeature\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AbstractFeature\&.AbstractFeature (int id, string name, Type type)"

.PP
Construtor da classe \fBAbstractFeature\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identificador do novo atributo\&.
.br
\fIname\fP Nome do novo atributo\&.
.br
\fItype\fP Tipo de dado do novo atributo\&.
.RE
.PP

.PP
Definition at line 31 of file AbstractFeature\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int AbstractFeature\&.id"

.PP
Identificador do atributo\&. 
.PP
Definition at line 13 of file AbstractFeature\&.cs\&.
.SS "string AbstractFeature\&.name"

.PP
Nome do atributo\&. 
.PP
Definition at line 18 of file AbstractFeature\&.cs\&.
.SS "string AbstractFeature\&.type"

.PP
Tipo de dado do atributo\&. 
.PP
Definition at line 23 of file AbstractFeature\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
