.TH "AbstractClasses/AbstractGlobalSimilarity.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractClasses/AbstractGlobalSimilarity.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractGlobalSimilarity\fP"
.br
.RI "Classe abstrata que representa uma medida de similaridade global que será implementada na biblioteca CBR\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
