.TH "AbstractClasses Directory Reference" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractClasses Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAbstractFeature\&.cs\fP"
.br
.ti -1c
.RI "file \fBAbstractGlobalSimilarity\&.cs\fP"
.br
.ti -1c
.RI "file \fBAbstractLocalSimilarity\&.cs\fP"
.br
.in -1c
