.TH "SimilarityMeasures Directory Reference" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilarityMeasures Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBGlobalSimilarities\fP"
.br
.ti -1c
.RI "directory \fBLocalSimilarities\fP"
.br
.in -1c
