.TH "SimilarityMeasures/LocalSimilarities Directory Reference" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilarityMeasures/LocalSimilarities Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEquals\&.cs\fP"
.br
.ti -1c
.RI "file \fBLinearFunction\&.cs\fP"
.br
.in -1c
