.TH "Core Directory Reference" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCase\&.cs\fP"
.br
.ti -1c
.RI "file \fBCaseBaseConnector\&.cs\fP"
.br
.ti -1c
.RI "file \fBCaseFeature\&.cs\fP"
.br
.ti -1c
.RI "file \fBCBRAPI\&.cs\fP"
.br
.ti -1c
.RI "file \fBConsultParams\&.cs\fP"
.br
.ti -1c
.RI "file \fBConsultStructure\&.cs\fP"
.br
.ti -1c
.RI "file \fBResult\&.cs\fP"
.br
.ti -1c
.RI "file \fBSearch\&.cs\fP"
.br
.in -1c
