.TH "Core/CaseFeature.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/CaseFeature.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCaseFeature\fP"
.br
.RI "Classe que representa um atributo presente na descrição do problema ou solução de um caso\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
