.TH "Core/Case.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Case.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCase\fP"
.br
.RI "Classe que representa um caso que compõem a base de casos\&. Composta por um identificador do caso e sua descrição do problema e solução\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
