.TH "Case" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Case \- Classe que representa um caso que compõem a base de casos\&. Composta por um identificador do caso e sua descrição do problema e solução\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCase\fP ()"
.br
.RI "Construtor da classe \fBCase\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Identificador do caso\&. "
.ti -1c
.RI "List< \fBCaseFeature\fP > \fBcaseDescription\fP"
.br
.RI "Descrição do problema a ser resolvido\&. "
.ti -1c
.RI "List< \fBCaseFeature\fP > \fBcaseSolution\fP"
.br
.RI "Descrição da solução utilizada para resolver o problema\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe que representa um caso que compõem a base de casos\&. Composta por um identificador do caso e sua descrição do problema e solução\&. 


.PP
Definition at line 8 of file Case\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Case\&.Case ()"

.PP
Construtor da classe \fBCase\fP\&. 
.PP
Definition at line 28 of file Case\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBCaseFeature\fP> Case\&.caseDescription"

.PP
Descrição do problema a ser resolvido\&. 
.PP
Definition at line 18 of file Case\&.cs\&.
.SS "List<\fBCaseFeature\fP> Case\&.caseSolution"

.PP
Descrição da solução utilizada para resolver o problema\&. 
.PP
Definition at line 23 of file Case\&.cs\&.
.SS "int Case\&.id"

.PP
Identificador do caso\&. 
.PP
Definition at line 13 of file Case\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
