.TH "CaseFeature" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CaseFeature \- Classe que representa um atributo presente na descrição do problema ou solução de um caso\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractFeature\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCaseFeature\fP (int \fBid\fP, string \fBname\fP, Type \fBtype\fP, object \fBvalue\fP)"
.br
.RI "Construtor da classe \fBCaseFeature\fP\&. "
.ti -1c
.RI "\fBCaseFeature\fP (int \fBid\fP, string \fBname\fP, Type \fBtype\fP)"
.br
.RI "Construtor da classe \fBCaseFeature\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBvalue\fP"
.br
.RI "Valor do atributo\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe que representa um atributo presente na descrição do problema ou solução de um caso\&. 


.PP
Definition at line 7 of file CaseFeature\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CaseFeature\&.CaseFeature (int id, string name, Type type, object value)"

.PP
Construtor da classe \fBCaseFeature\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identificador do atributo\&.
.br
\fIname\fP Nome do atributo\&.
.br
\fItype\fP Tipo de dado do atributo\&.
.br
\fIvalue\fP Valor do atributo\&.
.RE
.PP

.PP
Definition at line 21 of file CaseFeature\&.cs\&.
.SS "CaseFeature\&.CaseFeature (int id, string name, Type type)"

.PP
Construtor da classe \fBCaseFeature\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Identificador do atributo\&.
.br
\fIname\fP Nome do atributo\&.
.br
\fItype\fP Tipo de dado do atributo\&.
.RE
.PP

.PP
Definition at line 32 of file CaseFeature\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string CaseFeature\&.value"

.PP
Valor do atributo\&. 
.PP
Definition at line 12 of file CaseFeature\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
