.TH "Core/CBRAPI.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/CBRAPI.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCBRAPI\fP"
.br
.RI "Classe que deve ser instanciada para ser possível utilizar a biblioteca CBR\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
