.TH "ConsultStructure" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsultStructure \- Classe que contém a estrutura de consulta que será utilizada na análise de similaridade entre os casos\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsultStructure\fP ()"
.br
.RI "Construtor da classe \fBConsultStructure\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAbstractGlobalSimilarity\fP \fBglobalSimilarity\fP"
.br
.RI "Função de similaridade global que será utilizada na análise de similaridade de dois casos\&. "
.ti -1c
.RI "List< \fBConsultParams\fP > \fBconsultParams\fP"
.br
.RI "Lista de todos os parâmetros de consulta utilizados na análise de similaridade\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe que contém a estrutura de consulta que será utilizada na análise de similaridade entre os casos\&. 


.PP
Definition at line 8 of file ConsultStructure\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConsultStructure\&.ConsultStructure ()"

.PP
Construtor da classe \fBConsultStructure\fP\&. 
.PP
Definition at line 23 of file ConsultStructure\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBConsultParams\fP> ConsultStructure\&.consultParams"

.PP
Lista de todos os parâmetros de consulta utilizados na análise de similaridade\&. 
.PP
Definition at line 18 of file ConsultStructure\&.cs\&.
.SS "\fBAbstractGlobalSimilarity\fP ConsultStructure\&.globalSimilarity"

.PP
Função de similaridade global que será utilizada na análise de similaridade de dois casos\&. 
.PP
Definition at line 13 of file ConsultStructure\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
