.TH "Core/ConsultStructure.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/ConsultStructure.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConsultStructure\fP"
.br
.RI "Classe que contém a estrutura de consulta que será utilizada na análise de similaridade entre os casos\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
