.TH "Core/ConsultParams.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/ConsultParams.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConsultParams\fP"
.br
.RI "Classe que contém os parâmetros da consulta que serão utilizados para a análise de similaridade entre dois casos\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
