.TH "SimilarityMeasures/GlobalSimilarities/EuclideanDistance.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilarityMeasures/GlobalSimilarities/EuclideanDistance.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEuclideanDistance\fP"
.br
.RI "Classe que utiliza da função da Distância Euclidiana para calcular a similaridade global entre dois casos\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
