.TH "SimilarityMeasures/LocalSimilarities/LinearFunction.cs" 3 "Sun Nov 27 2016" "CBRAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimilarityMeasures/LocalSimilarities/LinearFunction.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLinearFunction\fP"
.br
.RI "Classe que utilizar uma função linear para calcular a similaridade local entre dois atributos do caso\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CBRAPI from the source code\&.
